-- inserting values into the table Students --

INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Sameer","Ohri","De Maisonneuve Boulevard,Montreal,Quebec","sameerohri44@gmail.com","1996-08-10","Male","STS","1");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Anmol","Preet","Jarry,Montreal,Quebec","kanmol77@gmail.com","1997-06-17","Female","STS","1");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Robin","Sharma","Cote Virtue,Montreal,Quebec","robinsharma40@gmail.com","1994-07-10","Male","STS","1");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Sophia","Chawla","Cote de Neiges,Montreal,Quebec","sophiachawla100@gmail.com","1995-08-05","Female","STS","1");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Rohit","Thapar","Lasalle,Montreal,Quebec","rocky1000@gmail.com","1996-10-23","Male","STS","1");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Aman","Kumar","Atwater,Montreal,Quebec","aman.kumar1@gmail.com","1994-02-14","Male","STS","2");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Manpreet","Mehta","Old Port,Montreal,Quebec","mannu44@gmail.com","1996-08-25","Female","STS","2");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Alex","Jackson","SnowDon,Montreal,Quebec","AlexJ100@yahoo.com","1996-10-08","Male","STS","2");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Sam","Collins","Decarie,Montreal,Quebec","sam.collins@gmail.com","1996-01-10","Female","STS","2");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Glenn","Maxwell","Villa Maria,Montreal,Quebec","glennmax1@gmail.com","1995-08-20","Male","STS","2");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Jos","Buttler","Verdun,Montreal,Quebec","josbuttler4@yahoo.com","1994-07-18","Male","MAD","3");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Emma","Gabriel","Lucien L'allier,Montreal,Quebec","EmmaGab44@hotmail.com","1998-06-10","Female","MAD","3");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Maria","Rutherford","Henri Bourassa,Montreal,Quebec","maria.r10@gmail.com","1996-05-27","Female","MAD","3");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Neha","Maria","Mont-Royal,Montreal,Quebec","marianeha33@gmail.com","1995-09-16","Female","MAD","3");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Nisha","Mahi","Guy-Concordia,Montreal,Quebec","nishamahi48@gmail.com","1997-12-10","Female","MAD","3");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Abraham","De villiers","Sauve,Montreal,Quebec","abdevillers444@gmail.com","1995-12-08","Male","MAD","4");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Baljinder","Singh","Beaubien,Montreal,Quebec","ballisingh3@gmail.com","1994-07-12","Male","MAD","4");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Mahima","Sharma","Acadie,Montreal,Quebec","mahisharma400@hotmail.com","1996-04-01","Female","MAD","4");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Anjali","Thakur","Parc,Montreal,Quebec","anju.thakur10@yahoo.com","1996-12-12","Female","MAD","4");
INSERT into Students(FirstName,LastName,Address,Email,DateOfBirth,Sex,ProgramName,GroupID)values("Ankush","Sharma","Namur,Montreal,Quebec","ankushsharma01@gmail.com","1994-01-17","Male","MAD","4");

-- inserting values into the table Teachers --

INSERT into Teachers(FirstName,LastName,Address,Email,DateOfBirth,Sex,HourlySalary)values("Eduardo","Amador","Rosemont,Montreal,Quebec","E.Amador100@gmail.com","1984-10-08","Male","85");
INSERT into Teachers(FirstName,LastName,Address,Email,DateOfBirth,Sex,HourlySalary)values("Yash","Patel","Bonaventure,Montreal,Quebec","yashpatel1990@gmail.com","1990-05-16","Male","80");
INSERT into Teachers(FirstName,LastName,Address,Email,DateOfBirth,Sex,HourlySalary)values("Brendon","Mccullum","Laurier,Montreal,Quebec","baz.mac17@gmail.com","1984-10-17","Male","95");
INSERT into Teachers(FirstName,LastName,Address,Email,DateOfBirth,Sex,HourlySalary)values("Zahra","Hasan","Outremont,Montreal,Quebec","zahrahasan50@yahoo.com","1988-03-14","Female","80");
INSERT into Teachers(FirstName,LastName,Address,Email,DateOfBirth,Sex,HourlySalary)values("Rucy","Edward","Jean-Talon,Montreal,Quebec","edward.rucy33@gmail.com","1986-02-18","Female","70");

-- inserting values into the table AcademicAdvisors --

INSERT into AcademicAdvisors(FirstName,LastName,Address,Email,DateOfBirth,Sex,YearlySalary)values("Mollie","Blouin","Georges Vanier,Montreal,Quebec","mollieblouin1987@gmail.com","1987-01-19","Female","60000");
INSERT into AcademicAdvisors(FirstName,LastName,Address,Email,DateOfBirth,Sex,YearlySalary)values("Andrew","Simmons","Berri-Uqam,Vanier,Montreal,Quebec","andrewsimmons200@gmail.com","1989-06-09","Male","50000");
INSERT into AcademicAdvisors(FirstName,LastName,Address,Email,DateOfBirth,Sex,YearlySalary)values("David","Watson","Saint Henri,Montreal,Quebec","watsondavid1@gmail.com","1982-08-21","Male","58000");

-- inserting values into the table Program --

INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("1","STS415","1");
INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("2","STS526","1");
INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("3","MAD314","2");
INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("4","MAD425","2");
INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("1","STS415","3");
INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("2","STS526","3");
INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("3","MAD314","3");
INSERT into Program(GroupID,GroupName,AcademicAdvisorID)values("4","MAD425","3");

-- inserting values into the table GroupOfProgram --

INSERT into GroupOfProgram(ProgramName,GroupNumber)values("STS","415");
INSERT into GroupOfProgram(ProgramName,GroupNumber)values("STS","526");
INSERT into GroupOfProgram(ProgramName,GroupNumber)values("MAD","314");
INSERT into GroupOfProgram(ProgramName,GroupNumber)values("MAD","425");

-- inserting values into the table Courses --

INSERT into Courses(CourseNumber,Subject,CourseHours)values("MAT101","MAT","45");
INSERT into Courses(CourseNumber,Subject,CourseHours)values("MAT202","MAT","45");
INSERT into Courses(CourseNumber,Subject,CourseHours)values("CSC111","CSC","60");
INSERT into Courses(CourseNumber,Subject,CourseHours)values("CSC222","CSC","60");
INSERT into Courses(CourseNumber,Subject,CourseHours)values("STT400","STT","90");
INSERT into Courses(CourseNumber,Subject,CourseHours)values("STT500","STT","90");

-- inserting values into the table Semesters --

INSERT into Semesters(Season,Year)values("Fall","2018");
INSERT into Semesters(Season,Year)values("Winter","2019");
INSERT into Semesters(Season,Year)values("Summer","2019");
INSERT into Semesters(Season,Year)values("Fall","2019");
INSERT into Semesters(Season,Year)values("Winter","2020");
INSERT into Semesters(Season,Year)values("Summer","2020");

-- inserting values into the table CourseOffering --

INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","1","1","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","1","2","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","1","3","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","1","4","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","2","4","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","2","2","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","2","3","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","2","1","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","3","1","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","3","5","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","3","3","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","3","4","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","4","2","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","4","5","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","4","3","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","4","4","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","5","1","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","5","3","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","5","4","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","5","5","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","6","3","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","6","4","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","6","2","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","6","5","1");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","1","1","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","1","2","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","1","3","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","1","4","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","2","4","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","2","2","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","2","3","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","2","1","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","3","1","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","3","5","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","3","3","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","3","4","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","4","2","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","4","5","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","4","3","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","4","4","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","5","1","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","5","3","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","5","4","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","5","5","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","6","3","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","6","4","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","6","2","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","6","5","2");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","1","1","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","1","2","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","1","3","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","1","4","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","2","4","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","2","2","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","2","3","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","2","1","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","3","1","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","3","5","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","3","3","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","3","4","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","4","2","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","4","5","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","4","3","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","4","4","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","5","1","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","5","3","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","5","4","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","5","5","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","6","3","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","6","4","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","6","2","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","6","5","3");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","1","1","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","1","2","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","1","3","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","1","4","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","2","4","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","2","2","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","2","3","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","2","1","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","3","1","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","3","5","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","3","3","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","3","4","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","4","2","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","4","5","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","4","3","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","4","4","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","5","1","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","5","3","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("4","5","4","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("5","5","5","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("1","6","3","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("2","6","4","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("3","6","2","4");
INSERT into CourseOffering(CourseID,SemesterID,TeacherID,GroupID)values("6","6","5","4");

-- inserting values into the table Grades --

INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","1","1","1","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","2","1","1","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","3","1","1","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","4","1","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","5","1","1","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","1","1","1","98");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","2","1","1","96");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","3","1","1","95");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","4","1","1","94");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","5","1","1","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","1","1","1","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","2","1","1","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","3","1","1","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","4","1","1","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","5","1","1","72");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","1","1","1","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","2","1","1","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","3","1","1","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","4","1","1","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","5","1","1","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","1","2","1","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","2","2","1","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","3","2","1","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","4","2","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","5","2","1","96");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","1","2","1","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","2","2","1","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","3","2","1","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","4","2","1","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","5","2","1","62");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","1","2","1","97");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","2","2","1","95");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","3","2","1","93");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","4","2","1","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","5","2","1","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","1","2","1","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","2","2","1","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","3","2","1","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","4","2","1","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","5","2","1","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","1","3","1","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","2","3","1","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","3","3","1","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","4","3","1","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","5","3","1","93");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","1","3","1","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","2","3","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","3","3","1","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","4","3","1","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","5","3","1","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","1","3","1","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","2","3","1","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","3","3","1","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","4","3","1","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","5","3","1","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","1","3","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","2","3","1","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","3","3","1","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","4","3","1","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","5","3","1","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","1","4","1","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","2","4","1","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","3","4","1","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","4","4","1","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","5","4","1","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","1","4","1","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","2","4","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","3","4","1","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","4","4","1","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","5","4","1","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","1","4","1","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","2","4","1","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","3","4","1","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","4","4","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","5","4","1","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","1","4","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","2","4","1","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","3","4","1","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","4","4","1","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","5","4","1","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","1","5","1","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","2","5","1","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","3","5","1","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","4","5","1","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","5","5","1","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","1","5","1","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","2","5","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","3","5","1","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","4","5","1","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","5","5","1","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","1","5","1","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","2","5","1","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","3","5","1","75");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","4","5","1","63");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","5","5","1","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","1","5","1","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","2","5","1","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","3","5","1","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","4","5","1","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","5","5","1","67");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","1","6","1","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","2","6","1","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","3","6","1","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","4","6","1","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","5","6","1","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","1","6","1","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","2","6","1","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","3","6","1","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","4","6","1","67");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","5","6","1","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","1","6","1","69");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","2","6","1","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","3","6","1","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","4","6","1","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","5","6","1","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","1","6","1","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","2","6","1","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","3","6","1","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","4","6","1","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","5","6","1","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","6","1","2","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","7","1","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","8","1","2","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","9","1","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","10","1","2","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","6","1","2","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","7","1","2","96");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","8","1","2","75");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","9","1","2","94");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","10","1","2","72");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","6","1","2","75");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","7","1","2","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","8","1","2","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","9","1","2","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","10","1","2","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","6","1","2","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","7","1","2","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","8","1","2","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","9","1","2","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","10","1","2","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","6","2","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","7","2","2","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","8","2","2","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","9","2","2","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","10","2","2","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","6","2","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","7","2","2","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","8","2","2","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","9","2","2","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","10","2","2","62");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","6","2","2","97");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","7","2","2","95");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","8","2","2","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","9","2","2","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","10","2","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","6","2","2","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","7","2","2","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","8","2","2","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","9","2","2","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","10","2","2","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","6","3","2","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","7","3","2","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","8","3","2","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","9","3","2","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","10","3","2","93");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","6","3","2","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","7","3","2","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","8","3","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","9","3","2","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","10","3","2","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","6","3","2","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","7","3","2","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","8","3","2","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","9","3","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","10","3","2","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","6","3","2","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","7","3","2","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","8","3","2","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","9","3","2","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","10","3","2","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","6","4","2","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","7","4","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","8","4","2","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","9","4","2","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","10","4","2","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","6","4","2","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","7","4","2","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","8","4","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","9","4","2","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","10","4","2","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","6","4","2","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","7","4","2","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","8","4","2","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","9","4","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","10","4","2","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","6","4","2","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","7","4","2","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","8","4","2","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","9","4","2","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","10","4","2","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","6","5","2","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","7","5","2","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","8","5","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","9","5","2","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","10","5","2","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","6","5","2","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","7","5","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","8","5","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","9","5","2","61");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","10","5","2","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","6","5","2","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","7","5","2","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","8","5","2","75");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","9","5","2","63");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","10","5","2","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","6","5","2","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","7","5","2","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","8","5","2","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","9","5","2","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","10","5","2","67");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","6","6","2","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","7","6","2","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","8","6","2","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","9","6","2","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","10","6","2","63");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","6","6","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","7","6","2","50");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","8","6","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","9","6","2","61");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","10","6","2","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","6","6","2","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","7","6","2","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","8","6","2","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","9","6","2","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","10","6","2","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","6","6","2","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","7","6","2","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","8","6","2","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","9","6","2","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","10","6","2","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","11","1","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","12","1","3","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","13","1","3","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","14","1","3","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","15","1","3","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","11","1","3","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","12","1","3","96");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","13","1","3","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","14","1","3","94");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","15","1","3","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","11","1","3","95");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","12","1","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","13","1","3","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","14","1","3","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","15","1","3","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","11","1","3","69");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","12","1","3","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","13","1","3","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","14","1","3","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","15","1","3","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","11","2","3","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","12","2","3","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","13","2","3","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","14","2","3","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","15","2","3","96");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","11","2","3","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","12","2","3","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","13","2","3","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","14","2","3","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","15","2","3","72");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","11","2","3","97");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","12","2","3","95");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","13","2","3","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","14","2","3","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","15","2","3","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","11","2","3","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","12","2","3","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","13","2","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","14","2","3","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","15","2","3","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","11","3","3","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","12","3","3","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","13","3","3","93");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","14","3","3","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","15","3","3","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","11","3","3","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","12","3","3","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","13","3","3","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","14","3","3","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","15","3","3","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","11","3","3","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","12","3","3","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","13","3","3","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","14","3","3","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","15","3","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","11","3","3","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","12","3","3","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","13","3","3","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","14","3","3","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","15","3","3","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","11","4","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","12","4","3","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","13","4","3","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","14","4","3","75");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","15","4","3","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","11","4","3","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","12","4","3","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","13","4","3","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","14","4","3","94");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","15","4","3","96");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","11","4","3","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","12","4","3","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","13","4","3","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","14","4","3","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","15","4","3","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","11","4","3","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","12","4","3","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","13","4","3","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","14","4","3","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","15","4","3","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","11","5","3","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","12","5","3","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","13","5","3","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","14","5","3","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","15","5","3","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","11","5","3","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","12","5","3","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","13","5","3","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","14","5","3","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","15","5","3","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","11","5","3","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","12","5","3","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","13","5","3","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","14","5","3","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","15","5","3","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","11","5","3","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","12","5","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","13","5","3","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","14","5","3","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","15","5","3","67");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","11","6","3","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","12","6","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","13","6","3","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","14","6","3","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","15","6","3","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","11","6","3","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","12","6","3","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","13","6","3","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","14","6","3","61");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","15","6","3","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","11","6","3","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","12","6","3","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","13","6","3","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","14","6","3","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","15","6","3","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","11","6","3","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","12","6","3","56");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","13","6","3","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","14","6","3","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","15","6","3","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","16","1","4","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","17","1","4","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","18","1","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","19","1","4","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","20","1","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","16","1","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","17","1","4","96");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","18","1","4","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","19","1","4","94");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","20","1","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","16","1","4","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","17","1","4","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","18","1","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","19","1","4","91");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","20","1","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","16","1","4","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","17","1","4","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","18","1","4","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","19","1","4","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","20","1","4","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","16","2","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","17","2","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","18","2","4","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","19","2","4","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","20","2","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","16","2","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","17","2","4","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","18","2","4","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","19","2","4","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","20","2","4","62");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","16","2","4","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","17","2","4","95");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","18","2","4","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","19","2","4","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","20","2","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","16","2","4","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","17","2","4","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","18","2","4","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","19","2","4","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","20","2","4","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","16","3","4","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","17","3","4","90");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","18","3","4","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","19","3","4","92");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","20","3","4","93");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","16","3","4","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","17","3","4","70");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","18","3","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","19","3","4","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","20","3","4","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","16","3","4","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","17","3","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","18","3","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","19","3","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","20","3","4","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","16","3","4","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","17","3","4","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","18","3","4","65");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","19","3","4","64");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","20","3","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","16","4","4","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","17","4","4","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","18","4","4","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","19","4","4","75");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","20","4","4","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","16","4","4","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","17","4","4","87");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","18","4","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","19","4","4","85");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","20","4","4","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","16","4","4","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","17","4","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","18","4","4","81");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","19","4","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","20","4","4","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","16","4","4","78");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","17","4","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","18","4","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","19","4","4","84");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","20","4","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","16","5","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","17","5","4","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","18","5","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","19","5","4","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","20","5","4","74");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","16","5","4","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","17","5","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","18","5","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","19","5","4","61");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","20","5","4","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","16","5","4","79");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","17","5","4","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","18","5","4","75");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","19","5","4","63");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("4","20","5","4","66");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","16","5","4","88");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","17","5","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","18","5","4","83");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","19","5","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("5","20","5","4","77");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","16","6","4","73");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","17","6","4","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","18","6","4","69");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","19","6","4","67");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("1","20","6","4","63");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","16","6","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","17","6","4","69");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","18","6","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","19","6","4","61");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("2","20","6","4","71");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","16","6","4","89");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","17","6","4","56");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","18","6","4","76");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","19","6","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("3","20","6","4","86");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","16","6","4","82");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","17","6","4","80");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","18","6","4","63");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","19","6","4","68");
INSERT into Grades(CourseID,StudentID,SemesterID,ProgramID,Grade)values("6","20","6","4","67");

-- Retrieving the data from the table Students --

SELECT * FROM Students;

-- Retrieving the data from the table Teachers --

SELECT * FROM Teachers;

-- Retrieving the data from the table AcademicAdvisors --

SELECT * FROM AcademicAdvisors;

-- Retrieving the data from the table Program --

SELECT * FROM Program;

-- Retrieving the data from the table GroupOfProgram --

SELECT * FROM GroupOfProgram;

-- Retrieving the data from the table Courses --

SELECT * FROM Courses;

-- Retrieving the data from the table Semesters --

SELECT * FROM Semesters;

-- Retrieving the data from the table CourseOffering --

SELECT * FROM CourseOffering;

-- Retrieving the data from the table Grades --

SELECT * FROM Grades;



